{
    "name": "Wholesale Shop POS Core",
    "summary": "Wholesale/retail POS support, purchase bill staging, vendor product mapping and price history",
    "version": "19.0.1.27.0",
    "category": "Sales/Point of Sale",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "product",
        "purchase",
        "stock",
        "account",
        "point_of_sale",
    ],
    "external_dependencies": {
        "python": [
            "numpy==1.26.4",
            "opencv-python==4.11.0.86",
            "Pillow>=10.2.0",
            "PyMuPDF==1.28.2",
        ],
    },
    "data": [
        "security/ir.model.access.csv",
        "views/res_partner_views.xml",
        "views/product_creation_wizard_views.xml",
        "views/purchase_import_views.xml",
        "views/purchase_order_views.xml",
        "views/vendor_product_map_views.xml",
        "views/bill_product_name_map_views.xml",
        "views/bill_ocr_template_views.xml",
        "views/price_history_views.xml",
        "views/product_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_views.xml",
        "views/user_menu_access_views.xml",
        "views/store_branding_views.xml",
    ],
    "assets": {
        "point_of_sale.customer_display_assets": [
            "wholesale_shop_pos/static/src/xml/store_customer_branding.xml",
        ],
        "point_of_sale._assets_pos": [
            "wholesale_shop_pos/static/src/xml/store_pos_branding.xml",
            "wholesale_shop_pos/static/src/js/pos_barcode_camera.js",
            "wholesale_shop_pos/static/src/xml/pos_barcode_camera.xml",
        ],
        "web.assets_backend": [
            "wholesale_shop_pos/static/src/js/store_branding.js",
            "wholesale_shop_pos/static/src/xml/store_branding.xml",
            "wholesale_shop_pos/static/src/js/product_image_search.js",
            "wholesale_shop_pos/static/src/xml/product_image_search.xml",
            "wholesale_shop_pos/static/src/js/line_name_crop.js",
            "wholesale_shop_pos/static/src/xml/line_name_crop.xml",
            "wholesale_shop_pos/static/src/js/product_barcode_field.js",
            "wholesale_shop_pos/static/src/xml/product_barcode_field.xml",
            ("after", "web/static/src/core/browser/router.js", "wholesale_shop_pos/static/src/js/store_router.js"),
            "wholesale_shop_pos/static/src/js/bill_image_preview.js",
            "wholesale_shop_pos/static/src/xml/bill_image_preview.xml",
            "wholesale_shop_pos/static/src/scss/bill_image_preview.scss",
            "wholesale_shop_pos/static/src/js/bill_camera_field.js",
            "wholesale_shop_pos/static/src/xml/bill_camera_field.xml",
            "wholesale_shop_pos/static/src/js/bill_crop_field.js",
            "wholesale_shop_pos/static/src/xml/bill_crop_field.xml",
            "wholesale_shop_pos/static/src/scss/bill_crop_field.scss",
            "wholesale_shop_pos/static/src/scss/purchase_import.scss",
        ],
    },
    "application": True,
    "installable": True,
}
