const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
let opened;
const ctx = vm.createContext({ Component: class {}, ImageField: class {}, imageField: {}, Dialog: class {}, FileUploader: class {},
    registry: { category: () => ({ add() {} }) }, _t: s => s, browser: { open: (...args) => { opened = args; } } });
vm.runInContext(fs.readFileSync('custom_addons/wholesale_shop_pos/static/src/js/product_image_search.js', 'utf8').replace(/^import .*;\r?\n/gm, '').replace(/^export /gm, ''), ctx);
const DialogClass = vm.runInContext('ProductImageSearchDialog', ctx), Field = vm.runInContext('ProductImageSearchField', ctx);
(async () => {
    const d = Object.create(DialogClass.prototype);
    d.state = { query: 'Tea & Coffee', automatic: false, busy: false };
    d.orm = { call: () => { throw Error('No API call should run without a key'); } };
    await d.search();
    assert.equal(opened[0], 'https://www.google.com/search?udm=2&q=Tea%20%26%20Coffee');
    assert.equal(opened[2], 'noopener,noreferrer');
    d.state.automatic = true;
    d.orm = { call: async () => [{ url: 'photo', title: 'Tea' }] };
    await d.search();
    assert.equal(d.state.results.length, 1);
    assert.equal(d.state.busy, false);
    let selected, closed = 0;
    d.props = { onApply: async data => { selected = data; }, close: () => { closed++; } };
    d.orm.call = async () => 'iPNGDATA';
    await d.choose({ url: 'photo' });
    assert.equal(selected, 'iPNGDATA');
    assert.equal(closed, 1);
    d.orm.call = async () => { d.destroyed = true; return 'STALE'; };
    await d.choose({ url: 'photo' });
    assert.equal(selected, 'iPNGDATA');
    d.destroyed = false;
    d.state.busy = false;
    await d.upload({ data: 'UPLOADED' });
    assert.equal(selected, 'UPLOADED');
    let popup, update;
    const f = Object.create(Field.prototype);
    f.props = { name: 'image_1920', readonly: false, record: { data: { name: 'Coffee' }, update: async data => { update = data; } } };
    f.state = { isValid: false };
    f.dialog = { add: (_, props) => { popup = props; } };
    f.openImageSearch();
    assert.equal(popup.query, 'Coffee');
    await popup.onApply('SELECTED');
    assert.equal(JSON.stringify(update), '{"image_1920":"SELECTED"}');
    assert.equal(f.state.isValid, true);
    f.props.readonly = true;
    await popup.onApply('IGNORED');
    assert.equal(update.image_1920, 'SELECTED');
    console.log('Passed: no-key Google link, search results, selection, cancelled request, upload, image-only update and read-only guard.');
})().catch(error => { console.error(error); process.exitCode = 1; });
